pageinfo = [[1666590160,973],
	[1673990075,9891],
	[1675703916,4030],
	[1666590160,3321],
	[1666590160,6778],
	[1666590160,204715],
	[1666590160,3517],
	[1673990075,1982],
	[1666590160,765],
	[1673990075,6598],
	[1666590160,15962],
	[1666590160,1139],
	[1673990075,14724],
	[1666590159,22217],
	[1673990075,7328],
	[1666590159,159773],
	[1666590159,139735],
	[1673990075,37717],
	[1666590161,3272],
	[1666590160,2114],
	[1666590160,4128],
	[1666590160,5399],
	[1675703916,7616],
	[1666590160,7465],
	[1666590160,18018],
	[1666590160,6105],
	[1673990075,15743],
	[1666590160,4960],
	[1666590160,15155],
	[1666590160,5335],
	[1666590160,4385],
	[1666590160,3059],
	[1666590161,7963],
	[1666590161,2132],
	[1666590161,2354],
	[1666590161,19596],
	[1666590161,21244],
	[1666590161,56096],
	[1666590161,2187],
	[1666590161,9395],
	[1666590161,25144],
	[1675703916,163954],
	[1666590161,310202],
	[1666590165,2537],
	[1666590165,812],
	[1666590159,10522],
	[1666590159,7780],
	[1666590165,753],
	[1666590196,408],
	[1666590196,8318],
	[1666590196,5750],
	[1666590196,1472],
	[1666590196,6489],
	[1673990075,1792],
	[1666590196,118818],
	[1666590196,134342],
	[1673990075,12778],
	[1666590196,910],
	[1666590197,5135],
	[1666590197,29355],
	[1666590197,608],
	[1675703916,2434],
	[1675703916,13383],
	[1666590198,1016],
	[1666590198,1829],
	[1675703916,47446],
	[1666590198,28607],
	[1666590198,27141],
	[1666590198,9053],
	[1666590198,12228],
	[1666590198,52293],
	[1666590198,14141],
	[1666590197,4016],
	[1666590197,46568],
	[1666590198,2013],
	[1666590197,14875],
	[1666590198,4297],
	[1666590198,4841],
	[1666590198,4523],
	[1666590198,11925],
	[1666590198,20302],
	[1666590159,1815637],
	[1666590159,9321],
	[1666590198,2023],
	[1666590159,929458],
	[1666590198,690],
	[1673990075,11847],
	[1666590198,727],
	[1666590198,69],
	[1666590198,65],
	[1666590198,65],
	[1666590199,1969],
	[1666590199,3050],
	[1666590199,1827],
	[1666590199,1775],
	[1666590199,1511],
	[1666590199,1563],
	[1666590199,4835],
	[1666590199,3303],
	[1666590199,2402],
	[1666590199,2373],
	[1666590199,9572],
	[1666590199,8713],
	[1666590199,3196],
	[1675703916,22035],
	[1666590199,3515],
	[1666590200,8517],
	[1666590200,540],
	[1675703916,2187],
	[1666590200,1642],
	[1666590200,14363],
	[1666590200,22969],
	[1666590210,5055],
	[1666590160,7800],
	[1666590210,4046],
	[1666590210,920],
	[1666590210,3810],
	[1666590210,2970],
	[1666590210,17741],
	[1666590210,2858],
	[1666590210,4631],
	[1666590210,16772],
	[1666590210,5005],
	[1666590210,5936],
	[1666590210,4945],
	[1666590210,4889],
	[1666590210,4848],
	[1666590210,2580]];
pagedata = [ ["about2.htm","About","Using the Help Files The help files are designed to familiarize users with the Cisco Packet Tracer interface, functions, and features. Although th...",""],
["AccessibilityBasics.htm","Accessibility","Accessibility Cisco Packet Tracer supports screen readers, tab navigation, keyboard shortcuts, high contrast support, and high DPI scaling. There ...",""],
["acknowledgements.htm","Acknowledgments","Packet Tracer Development Team Original Packet Tracer Concept and Design Dennis Frezzo Michael Wang Mark Chen Brad Anderson Development Team Franc...",""],
["activityWizard.htm","Activity Wizard","Activity Wizard The Activity Wizard is an assessment tool that allows you to create highly specific networking scenarios for other users. You can ...",""],
["activityWizard_answerNetwork.htm","Answer Network","Answer Network In the Answer Network panel, you construct the answer network, and mark the elements of the network on which you want to assess the...",""],
["activityWizard_assessmentItems.htm","Assessment Items","Assessment Items What are Assessment Items? The assessment items are found in the Assessment Items tab of the Answer Network section in the Activi...",""],
["activityWizard_initialNetwork.htm","Initial Network","Initial Network In the Initial Network panel, you set the network from which the user will start the activity. One option for setting up the initi...",""],
["activityWizard_instructions.htm","Instructions","Instructions The student instructions for the activity are entered in the Instructions panel. When students open the activity file, the instructio...",""],
["activityWizard_password.htm","Password","Password The Password panel allows you to set a password for the Activity Wizard features of the activity file. If no password is set, anyone who ...",""],
["activityWizard_run.htm","Running Activity Files","Running Activity Files You start an activity by opening a saved activity (.pka) file. You will first see the Activity window telling you how to co...",""],
["activityWizard_scoringModelAndScripting.htm","Scoring Model/Scripting","Scoring Model/Scripting The Scoring Model is an Evidence Centered Design process by which to assess work products through the application of scori...",""],
["activityWizard_test.htm","Testing/Checking the Activity (Previewing)","Testing/Checking the Activity (Previewing) When you choose the Test Activity tab from the Activity Menu, you can do a trial run of the activity yo...",""],
["activityWizard_variableManager.htm","Variable Manager","Variable Manager The Variable Manager provides the ability for an activity author to add dynamic capabilities into an activity. These capabilities...",""],
["CLI_asa.htm","Supported Commands: ASA","ASA Packet Tracer uses a simplified model of the Cisco Adaptive Security Appliance Software. Click on the CLI tab in the ASA configuration window ...",""],
["CLI_router829.htm","Cisco IOS Supported Commands: Router 829","Router 829: IOS/IOX 829 Industrial Integrated Services Routers are compact Cisco IOS Software routers with support for integrated 4G LTE wireless ...",""],
["CLI_routerIOS.htm","Cisco IOS Supported Commands: Routers","Routers: IOS Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the router configuration window to access the Cisco I...",""],
["CLI_routerIOS15.htm","Cisco IOS 15 Supported Commands: Routers","Routers: IOS 15 Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the router configuration window to access the Cisc...",""],
["CLI_switchIOS.htm","Cisco IOS Supported Commands: Switches","Switches: IOS Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the switch configuration window to access the Cisco ...",""],
["configuringDevices.htm","Configuring Devices","Configuring Devices As with real networks, the networks you make in Packet Tracer must be properly configured before they \"work.\" For simple devic...",""],
["config_asa.htm","Configuring ASA","Configuring ASA The Config tab for the ASA offers four general levels of configuration: global, clientless vpn, switching, and interface. The glob...",""],
["config_clouds.htm","Configuring Clouds","Configuring Clouds The Config tab offers three general levels of configuration: global, connections, and interface. To configure at the global lev...",""],
["config_HomeRouter.htm","Configuring Tri-Band Home Router","Configuring Tri-Band Wireless Home Router The Config tab offers two general levels of configuration: global and interface. To configure at the glo...",""],
["config_IE2000.htm","Configuring ASA","Configuring IE 2000 The Config tab for the IE 2000 offers four general levels of configuration: global, switching, and interface. The global level...",""],
["config_MerakiDevices.htm","Configuring Tri-Band Home Router","Configuring Meraki Devices Cisco Packet Tracer supports a simplified version of the Meraki Security Appliance (SA), MX65W, and a cloud based Merak...",""],
["config_NetworkControllers.htm","Configuring PCs","Configuring Network Controllers Cisco Packet Tracer supports a simplified version of the Network Controller device. Overview Network Controller (N...",""],
["config_others.htm","Configuring Other Devices","Configuring Other Devices The configuration options for all other devices are relatively simple. In general, you can change their display names in...",""],
["config_PCs.htm","Configuring PCs","Configuring PCs, Laptops, Tablet PCs, and PDAs You can configure the global settings and interface settings on the PC, laptop, tablet PC, and PDA ...",""],
["config_routers.htm","Configuring Routers","Configuring Routers The Config tab offers four general levels of configuration: global, routing, switching (Cisco 1841 and Cisco 2811 only), and i...",""],
["config_servers.htm","Configuring Servers","Configuring Servers The Config tab offers two levels of configuration: global, and interface. To configure at the global level, click the GLOBAL b...",""],
["config_switches.htm","Configuring Switches","Configuring Switches The Config tab for the switch offers three general levels of configuration: global, switching, and interface. The global leve...",""],
["config_WLCs.htm","Configuring Wireless LAN Controllers","Configuring Wireless LAN Controllers The Config tab of the Wireless LAN Controller (WLC) offers two general levels of configuration: global and in...",""],
["config_wrt300n.htm","Configuring WRT300N","Configuring WRT300N The Config tab offers two general levels of configuration: global and interface. To configure at the global level, click the G...",""],
["connectionsLinks.htm","Connections / Links","Connections / Links Packet Tracer supports a wide range of network connections. Each cable type can only be connected to certain interface types. ...",""],
["copyrights.htm","No title","DOWNLOADING, INSTALLING, OR USING THE CISCO PACKET TRACER SOFTWARE CONSTITUTES ACCEPTANCE OF THE CISCO END USER LICENSE AGREEMENT (&#8220;EULA&#8221; https://...",""],
["devicesAndModules.htm","Devices and Modules","Devices and Modules Packet Tracer supports a wide array of modules for networking devices. To change a module in any device, you must first turn o...",""],
["devicesAndModules_endDevices.htm","Devices and Modules: End Devices","Devices and Modules: End Devices All images on this page are thumbnails in which you can click to bring up a larger image. PC-PT The PC-PT provide...",""],
["devicesAndModules_others.htm","Devices and Modules: Other Devices","Devices and Modules: Other Devices All images on this page are thumbnails on which you can click to bring up a larger image. Hub-PT The Hub-PT pro...",""],
["devicesAndModules_routers.htm","Devices and Modules: Routers","Devices and Modules: Routers All images on this page are thumbnails on which you can click to bring up a larger image. Router: ISR4321 The Cisco 4...",""],
["devicesAndModules_structuredCabling.htm","Devices and Modules: Other Devices","Devices and Modules: Structured Cabling Devices Structured Cabling Devices are a special class of devices that are only visible in Physical View. ...",""],
["devicesAndModules_switches.htm","Devices and Modules: Switches","Devices and Modules: Switches All images on this page are thumbnails on which you can click to bring up a larger image. Switch: 2960-24TT The Cisc...",""],
["environment.htm","Environment","Environment The intercity, city, buildings, wiring closets, and generic containers all have an environment. There are a couple dozen default envir...",""],
["faqTroubleShoot.htm","Frequently Asked Questions (FAQ)/Troubleshoot Guide","Frequently Asked Questions (FAQ)/Troubleshooting Guide Topics General Specific Protocol Modeling Internet of Things General Issues 1. What Cisco I...",""],
["files/CiscoPacketTracerPTMPSpecification.pdf","CiscoPacketTracerPTMPSpecification.pdf","Cisco Packet Tracer Packet Tracer Messaging Protocol (PTMP) Specification Document Copyright Cisco 2020 Modification History Revision Date Origina...",""],
["fontPreference.htm","Font Setting and 4k Support","Font Setting and 4k Support Font preference User can adjust font size, family and color for different application User Interfaces (UI), there are ...",""],
["gettingStarted.htm","Getting Started","Getting Started The best place to get started is to review the help files. The help files contain comprehensive documentation on almost all the fe...",""],
["GUI_HomeRouter.htm","Tri-Band Home Router: GUI","Tri-Band Home Router: GUI The GUI tab offers the same configurations and settings as the Config tab with some additional features for access restr...",""],
["GUI_wrt300n.htm","WRT300N: GUI","WRT300N: GUI The GUI tab offers the same configurations and settings as the Config tab with some additional features for access restrictions, port...",""],
["high_Contrast.htm","High Contrast Support","High Contrast Support Cisco Packet Tracer supports high contrast using the operating system&#39;s high contrast theme. The high contrast themes on the...",""],
["index.htm","Cisco Packet Tracer Help","",""],
["interfaceOverview.htm","Interface Overview","Interface Overview When you open Packet Tracer, by default you will be presented with the following interface: This initial interface contains ten...",""],
["intro.htm","Introduction","Introduction Welcome to Cisco Packet Tracer. Packet Tracer is a medium fidelity, network-capable, simulation-based learning environment for networ...",""],
["iot.htm","Internet of Things","Internet of Things Included in this version of Packet Tracer are a variety of networked physical objects or Things. There are Smart Things that ar...",""],
["iot_creating_things.htm","Creating Things","Creating Things All Things, Smart Things and Components in Packet Tracer use the same base device: Thing. What makes them unique is the configurat...",""],
["iot_ios_iox.htm","Visual API","IOS and IOx Cisco IOS Software is the world&#39;s leading network infrastructure software, delivering a seamless integration of technology innovation,...",""],
["iot_javascript_api.htm","JavaScript API","JavaScript API Program Structure and Events Function Return Type Description Example setup() N/A If defined, this function is called once when the...",""],
["iot_python_api.htm","Python API","Python API Program Structure and Events Package = N/A Function Return Type Description Example cleanUp() N/A If defined, this function is called o...",""],
["iot_using_things.htm","Using Things","Using Things Where are the Things? In addition to routers and switches, the Network Component Box now contains a variety of Smart Things and compo...",""],
["iot_visual_api.htm","Visual API","Visual API In addition to JavaScript and Python, Packet Tracer supports programming using a WYSIWYG interface based on Blockly. All the supported ...",""],
["ipc.htm","IPC","IPC (Inter-Process Communication) The IPC (Inter-Process Communication) feature controls an external programming extension for Packet Tracer that ...",""],
["keyboardShortcuts.htm","Keyboard Shortcuts","?Keyboard Shortcuts Many actions in Packet Tracer are keyboard-accessible for your convenience. In addition to key combinations, the following key...",""],
["large_Interface.htm","High DPI Scaling","High DPI scaling Cisco Packet Tracer supports high DPI scaling across various operating Systems. You can enlarge the entire interface and text usi...",""],
["login.htm","Log In","Log In Cisco Packet Tracer requires user authentication. A NetAcad or a SkillsForAll account is required to sign in when you launch Cisco Packet T...",""],
["menu.htm","Main Menu","? Packet Tracer Search Introduction What&#39;s New Program Usage Log In Getting Started Interface Overview Preferences User Profile Font Setting/4K Su...",""],
["modeling.htm","Modeling in Packet Tracer","Modeling in Packet Tracer Packet Tracer simulates the behavior of real networks and devices using models. As with all simulations, the program is ...",""],
["model_layer1.htm","Layer 1 Models","Layer 1 Models How hubs process frames When a hub receives a frame ( flowchart here): If two or more ports receive frames at the same time, a coll...",""],
["model_layer2.htm","Layer 2 Models","Layer 2 Models How switches process incoming frames When a switch receives a frame ( flowchart here): It compares the receiving port&#39;s type (trunk...",""],
["model_layer3IP.htm","Layer 3 IP Models","Layer 3 IP Models How IP and IPv6 are modeled Packet Tracer models only certain aspects of IP. IP version 4 is modeled. IP addresses are 32 bits l...",""],
["model_layer3Routing.htm","Layer 3 Routing Models","Layer 3 Routing Models - RIPv1 RIPv2 EIGRP OSPF How a router starts the RIP process The router generates a RIP request packet to be sent out all p...",""],
["model_layer4.htm","Layer 4 Models","Layer 4 Models How devices process UDP segments This procedure explains how a device sends and receives UDP segments. When the device receives a s...",""],
["model_layer5.htm","Layer 5 Models","Layer 5 Models How Routers Handle ISAKMP Segments When a router sends an ISAKMP segment ( flowchart here): If a packet is getting out of the devic...",""],
["model_layer7.htm","Layer 7 Models","Layer 7 Models How DHCP clients work DHCP client sends a DHCP-DISCOVER packet ( flowchart here): When a DHCP client device receives a packet: It d...",""],
["model_misc.htm","Other Models","Other Models How routers process incoming packets (NAT process) When a router receives a packet: It checks if the receiving port is a NAT outside ...",""],
["mode_realtime.htm","Realtime Mode","Realtime Mode In Realtime Mode, your network is always running (like a real network) whether you are working on the network or not. Your configura...",""],
["mode_simulation.htm","Simulation Mode","Simulation Mode In Simulation Mode, you can watch your network run at a slower pace, observing the paths that packets take and inspecting them in ...",""],
["mode_simulation_complexPDUs.htm","Simulation Mode: Complex PDUs","Simulation Mode: Complex PDUs In addition to simple, quick pings, you can also send customized PDUs. In the Common Tools Bar, click the Add Comple...",""],
["mode_simulation_PDUcolor.htm","PDU Color Legend","PDU Color Legend PDU Type Hex Value Actual Color AAA Radius Client Process 0xedd170 AAA Radius Server Process 0xedd170 AAA Tacacs Client Process 0...",""],
["mode_simulation_PDUinfo.htm","Simulation Mode: PDU Information","Simulation Mode: PDU Information During a simulation, you can click on a packet (on the topology or the corresponding event in the Event List) to ...",""],
["mode_simulation_Scenarios.htm","Simulation Mode: Managing Simulation Scenarios","Simulation Mode: Managing Simulation Scenarios In Packet Tracer, you can set up and simulate complex networking situations (scenarios) through the...",""],
["mode_simulation_specialNotes.htm","Simulation Mode: Special Notes","Simulation Mode: Special Notes Editing the Network and Using the Cisco IOS in Simulation Mode Although Realtime Mode is the preferred mode for net...",""],
["multiuser.htm","Multiuser","Multiuser Multiuser communication allows multiple point-to-point (peer) connections between multiple instances of Packet Tracer. By allowing commu...",""],
["myFirstPTLab.htm","My First Packet Tracer Lab","? My First Packet Tracer Lab Introduction Welcome to Packet Tracer. Research has shown that users who master a few basic tasks when first starting...",""],
["NetconRestAPI/index.html","Cisco Packet Tracer Northbound API for Network Controller Device","API Summary Tickets addTicket deleteTicket Inventory addNetworkDevice deleteNetworkDeviceById deleteNetworkDeviceByIp getNetworkDeviceById getNetw...",""],
["OpenSSL_License.htm","OpenSSL Liscense","OpenSSL License License Issues The OpenSSL toolkit stays under a dual license, i.e. both the conditions of the OpenSSL License and the original SS...",""],
["operatingModes.htm","Operating Modes","Operating Modes Packet Tracer operating modes reflect the network time scheme. In Realtime Mode, your network runs in a model of real time, within...",""],
["PacketTracerOpenSource.pdf","PacketTracerOpenSource.pdf","Open Source Used In Cisco Packet Tracer 8.2 Cisco Systems, Inc. www.cisco.com Cisco has more than 200 offices worldwide. Addresses, phone numbers,...",""],
["portConstants.htm","Known Used Ports","? Known Used Ports Packet Tracer uses the following ports. Multi-user 38000~ Assessment 39000~ ",""],
["preferences.htm","Settings and Preferences","Settings and Preferences Preferences You can customize your Packet Tracer experience by setting your own preferences. From the Menu Bar, select Op...",""],
["programming.htm","Programming","Programming Programming is the logic that makes the devices function. Packet Tracer supports three different scripting languages: Javascript, Pyth...",""],
["programming_javascript.htm","No title","",""],
["programming_python.htm","No title","",""],
["programming_visual.htm","No title","",""],
["sampleFilesAndDesignPatterns.htm","Sample Files, File Compatibility, and Design Patterns","Sample Files, File Compatibility, and Design Patterns There are over 300 Packet Tracer .pka files that exist embedded in the Discovery and Explora...",""],
["sampleFilesAndDesignPatterns_conceptBuilder.htm","Concept Builders","Concept Builders Concept builders are model-building inquiries and investigations leading to student-created explanations and animations of networ...",""],
["sampleFilesAndDesignPatterns_design.htm","Design Challenges","Design Challenges Design challenges are constraint-based problems with multiple correct solutions. They may range from very simple (devise a class...",""],
["sampleFilesAndDesignPatterns_skillBuilder.htm","Skill Builders","Skill Builders Skill builders support algorithmic problem solving in support of the development of networking procedural knowledge. For example, s...",""],
["sampleFilesAndDesignPatterns_troubleshoot.htm","Troubleshooting","Troubleshooting Troubleshooting activities include diagnosing, isolating, and fixing the simulated network from a previously bugged network file. ...",""],
["screenreader_basics.htm","Screen Reader Basics","Screen Reader Basics Cisco Packet Tracer supports screen readers for all buttons on the application window and dialogs. Screen readers should read...",""],
["scriptModules.htm","Script Modules","Script Modules Script Modules are independent entities that add new functionality to Packet Tracer similar to External Applications (ExApps). But ...",""],
["scriptModules_customUdp.htm","Script Modules","Script Modules - Custom UDP Processes With Script Modules, instructors and students can now develop and add new protocols to PT. They are called c...",""],
["scriptModules_dataStore.htm","Script Modules","Script Modules - Data Store The data store is the other part of the model in the Script Module. The data store has a list of data files, in json, ...",""],
["scriptModules_data_store_editor.htm","DataStore Editor","Data Store Editor Besides using the Data Store Tab that was mentioned in Script Modules - Data Store , Packet Tracer also allows users to edit the...",""],
["scriptModules_scriptEngine.htm","Script Modules","Script Modules - Script Engine Each Script Module has one instance of a Qt Script Engine. A Script Module can contain multiple script files writte...",""],
["scriptModules_scriptingInterface.htm","Script Modules","Script Modules - Scripting Interface The Scripting Interface is the Script Module development environment inside PT. This is extended from the Scr...",""],
["scriptModules_tips.htm","Script Modules","Script Modules - Tips The dprint() function is per Script Module. Check the Debug Dialog of the correct Script Module for these outputs. Changes m...",""],
["scriptModules_webViews.htm","Script Modules","Script Modules - Web Views Web Views Web views are using the QWebEngine functionality to render HTML5. Script Modules use web views to create cust...",""],
["search.html","Search","Search Enter keyword(s) to search. ",""],
["shapetest.htm","Shape Tests","Shape Test Students can draw around a feature in the network that can be scored in the Activity Wizard Shape Tests is an activity feature in Packe...",""],
["support.htm","Packet Tracer Support and Contact Information","Packet Tracer Support and Contact Information Please contact the Academy Help Desk, or report a Packet Tracer bug by clicking on \"Help &#166; Report an...",""],
["systemRequirements.htm","System Requirements","?System Requirements 64 bit amd64(x86-64) CPU Computer with one of the following operating systems: Microsoft Windows 10 (64bit) and 11 (64bit), U...",""],
["tab_Navigation.htm","Tab Navigation","Tab Navigation User can navigate accross Packet Tracer using the &#39;TAB&#39; and the &#39;Arrow&#39; keys. Selections may be activated via either the &#39;Space&#39; ke...",""],
["timeConstants.htm","Time Constants","Time Constants Packet Tracer uses the following time constants: RIP/RIPv6 default update 30 secs RIP/RIPv6 default timeout 3 mins RIP/RIPv6 defaul...",""],
["translation.htm","Packet Tracer Translation Process","Packet Tracer Translation Process Packet Tracer supports semi-automated translation to all Unicode-supported languages. The first part of this gui...",""],
["usesForPT.htm","Uses for Packet Tracer","Uses for Packet Tracer For Students Welcome to the world of computer networking. Packet Tracer can be a fun, take-home, flexible piece of software...",""],
["WebEngineViewsAccessibility.htm","WebEngine Views Accessibility","WebEngine Views Accessibility The following table shows the compatibility matrix between the webview UI in Cisco Packet Tracer and the default scr...",""],
["whatsNew.htm","What&#39;s New","What&#39;s New Users of previous versions of Packet Tracer will note a variety of new features in Packet Tracer 8. New in version 8.2.0 New command \"s...",""],
["workspaceBasics.htm","The Logical and Physical Workspaces","The Logical and Physical Workspaces Packet Tracer uses two representation schemes for your network: the Logical Workspace and the Physical Workspa...",""],
["workspacelist.htm","Workspace List","Workspace List This view provides a list style representation of the current visible logical workspace. In situations where keyboard navigation an...",""],
["workspaceViewport.htm","Workspace Viewports","Workspace Viewport Panels Workspace Viewport Panel (Viewport in short) is a panel showing a part or the entire workspace area. This panel is espec...",""],
["workspace_logical.htm","The Logical Workspace","The Logical Workspace The Logical Workspace is where you will spend the majority of your time building and configuring your network. In conjunctio...",""],
["workspace_logical_creating_custom_templates.htm","Creating Custom Templates","Creating Custom Templates Creating Custom Templates The Device Template Manager allows you to save devices, clusters, and physical containers as t...",""],
["workspace_logical_customIconsAndBG.htm","The Physical Workspace: Moving Devices","Customizing Icons and Backgrounds (BG) Using Custom Icons Icons that represent devices in Packet Tracer in both Logical and Physical mode can now ...",""],
["workspace_physical.htm","The Physical Workspace","The Physical Workspace The purpose of the Physical Workspace is to give a physical dimension to your logical network topology. It gives you a sens...",""],
["workspace_physical_accessibility.htm","The Physical Workspace: Accessibility Navigation","The Physical Workspace: Accessibility Navigation The Physical Workspace allows support with third party screen reader applications, such as Micros...",""],
["workspace_physical_cableManipulation.htm","The Physical Workspace: Cable Manipulation","The Physical Workspace: Cable Manipulation In Physical Workspace, cables can be manipulated to provide a more realistic representation of a physic...",""],
["workspace_physical_customIconsAndBG.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Customizing Icons and Backgrounds (BG) Using Custom Icons Icons that represent devices in Packet Tracer in both Logical an...",""],
["workspace_physical_distanceMeasurements.htm","The Physical Workspace: Distance Measurements","The Physical Workspace: Distance Measurements The Physical Workspace provides the dimension of distance to Ethernet and wireless devices. This dis...",""],
["workspace_physical_movingDevices.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Moving Devices The Physical Workspace allows you to move your devices to various locations. To move devices up or down the...",""],
["workspace_physical_specialNotes.htm","The Physical Workspace: Special Notes","The Physical Workspace: Special Notes Navigation Panel You can click on the Navigation button from the Physical Workspace Bar to bring up the navi...",""]];
